disabled_rules:
    - line_length
    - trailing_whitespace
    - identifier_name
    - function_body_length
    - type_body_length
enabled_rules:
    - closure_spacing
excluded:
- Pods
- AppStoreClone/Extensions
